# Sync API secrets from ~/secrets/hai-verify.env → Cloudflare Workers
# Usage: powershell -ExecutionPolicy Bypass -File ./scripts/sync-workers-env.ps1

$ErrorActionPreference = "Stop"
$root = Split-Path -Parent (Split-Path -Parent $MyInvocation.MyCommand.Path)
. (Join-Path $root "scripts\lib\with-user-context.ps1")
Enter-ScriptWithUserContext -Strict
Set-Location $root

$envFile = Join-Path $env:USERPROFILE "secrets\hai-verify.env"
if (-not (Test-Path $envFile)) {
  $envFile = Join-Path $root ".env.local"
}
if (-not (Test-Path $envFile)) {
  Write-Host "Missing secrets file: $envFile"
  exit 1
}

$vaultScript = Join-Path $PSScriptRoot "lib\secrets-vault.ps1"
$vaultJson = & $vaultScript export-json 2>$null
$vaultSecrets = @{}
if ($vaultJson) {
  $vaultSecrets = $vaultJson | ConvertFrom-Json -AsHashtable
}

$parsed = @{}
Get-Content $envFile | ForEach-Object {
  $line = $_.Trim()
  if ($line -match '^#|^$') { return }
  if ($line -match '^([^=]+)=(.*)$') {
    $parsed[$matches[1].Trim()] = $matches[2].Trim()
  }
}

# Load Cloudflare deploy credentials (not uploaded to Workers)
foreach ($cfKey in @('CLOUDFLARE_API_TOKEN', 'CLOUDFLARE_ACCOUNT_ID')) {
  $cfVal = $vaultSecrets[$cfKey]
  if (-not $cfVal) { $cfVal = $parsed[$cfKey] }
  if ($cfVal) { Set-Item -Path "env:$cfKey" -Value $cfVal }
}

$hasCfToken = [bool]$env:CLOUDFLARE_API_TOKEN

# Worker runtime secrets (encrypted in Cloudflare)
$secretKeys = @(
  'OPENAI_API_KEY',
  'HAI_API_KEY_SECRET',
  'HAI_INTERNAL_API_KEY',
  'STRIPE_SECRET_KEY',
  'STRIPE_WEBHOOK_SECRET',
  'STRIPE_PRICE_STARTER',
  'STRIPE_PRICE_PRO',
  'NEXT_PUBLIC_STRIPE_PUBLISHABLE_KEY'
)

$bulk = @{}
foreach ($key in $secretKeys) {
  $val = $vaultSecrets[$key]
  if (-not $val) { $val = $parsed[$key] }
  if ($val -and $val -notmatch '\.\.\.|^<|your_|placeholder') {
    $bulk[$key] = $val
  }
}

if ($bulk.Count -eq 0) {
  Write-Host "No worker secrets found to upload in $envFile"
  exit 1
}

if ($hasCfToken) {
  $tmpJson = Join-Path $env:TEMP "hai-verify-workers-secrets.json"
  $bulk | ConvertTo-Json -Compress | Set-Content $tmpJson -Encoding UTF8

  Write-Host "Uploading $($bulk.Count) secret(s) to Workers (hai-verify)..."
  npx wrangler secret bulk $tmpJson
  if ($LASTEXITCODE -ne 0) { exit $LASTEXITCODE }

  Remove-Item $tmpJson -Force -ErrorAction SilentlyContinue
} else {
  Write-Host "SKIP Workers upload — CLOUDFLARE_API_TOKEN not set in $envFile"
  Write-Host "Add CLOUDFLARE_API_TOKEN + CLOUDFLARE_ACCOUNT_ID, then re-run."
}

# Local wrangler preview (.dev.vars) — exclude Cloudflare deploy credentials
$devVarsPath = Join-Path $root ".dev.vars"
$devLines = @(
  "# Auto-generated by sync-workers-env.ps1 — do not commit",
  "HAI_ACCESS_MODE=protected",
  "HAI_ACCESS_LOCAL_BYPASS=true"
)
foreach ($key in $secretKeys) {
  if ($bulk.ContainsKey($key)) {
    $devLines += "$key=$($bulk[$key])"
  }
}
$devLines | Set-Content $devVarsPath -Encoding UTF8
Write-Host "Wrote local preview env: .dev.vars"

Write-Host ""
Write-Host "Done."
if ($hasCfToken) { Write-Host "Verify remote: npx wrangler secret list" }
Write-Host "Public vars in wrangler.jsonc: HAI_ACCESS_MODE=protected, HAI_ACCESS_LOCAL_BYPASS=false"